Task2 GUI
sergey-berezin/441_belyaeva pull request #2
Opened 2021-11-09 19:00 UTC by yaaawner

2021-11-10 06:19 UTC, sergey-berezin requested changes

2021-11-10 06:19 UTC, sergey-berezin commented on WpfApp/MainWindow.xaml.cs
> +    abstract public class Type
Эти типы лучше переместить в конец файла или в отдельный файл.

2021-11-10 06:19 UTC, sergey-berezin commented on WpfApp/MainWindow.xaml.cs
> +        private async void btnRun_Click(object sender, RoutedEventArgs e)
Надо защититься от возможности повторного входа в обработчик

2021-11-10 06:19 UTC, sergey-berezin commented on WpfApp/MainWindow.xaml.cs
> +            //await Task.WhenAll(Detector.DetectImage(TextBox_Path.Text), Consumer());
Ненужные комментарии надо удалить.

2021-11-10 06:19 UTC, sergey-berezin commented on WpfApp/MainWindow.xaml.cs
> +    abstract public class Type
Тип `Type` и наследование здесь избыточны.

2021-11-22 20:36 UTC, yaaawner commented on WpfApp/MainWindow.xaml.cs
> +    abstract public class Type
done

2021-11-22 21:11 UTC, yaaawner commented on WpfApp/MainWindow.xaml.cs
> +        private async void btnRun_Click(object sender, RoutedEventArgs e)
done

2021-11-22 21:23 UTC, yaaawner commented on WpfApp/MainWindow.xaml.cs
> +    abstract public class Type
done

2021-11-22 21:23 UTC, yaaawner commented on WpfApp/MainWindow.xaml.cs
> +            //await Task.WhenAll(Detector.DetectImage(TextBox_Path.Text), Consumer());
done

2021-11-24 06:09 UTC, merged